#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Wed Aug 05 10:05:46 GMT 2026
org.gradle.caching=true
android.nonTransitiveRClass=true
org.gradle.daemon.idletimeout=10800000
systemProp.user.country=US
systemProp.user.language=en
org.gradle.tooling.parallel=true
org.gradle.daemon=true
markwonVersion=4.6.2
org.gradle.parallel=false
targetSdkVersion=28
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
minSdkVersion=23
kotlin.code.style=official
compileSdkVersion=36
systemProp.sun.jnu.encoding=UTF-8
ndkVersion=29.0.14033849
systemProp.file.encoding=UTF-8
org.gradle.configureondemand=true
